Add localization.md
dotnet/project-system pull request #7555
Opened 2021-09-02 04:37 UTC by drewnoakes

Capture some information about the localization process in the repo's documentation.

2021-09-02 04:38 UTC, drewnoakes commented
Feel free to extend the doc with whatever info would be useful.

2021-09-02 15:58 UTC, jjmew approved these changes

2021-09-02 17:29 UTC, MiYanni requested changes
The file has no file extension. The content looks good. 👍

2021-09-03 01:02 UTC, MiYanni approved these changes

2021-09-03 01:15 UTC, MiYanni approved these changes

2021-09-03 02:26 UTC, merged