Don't indent case contents when block
dotnet/project-system pull request #7907
Opened 2022-02-09 09:01 UTC by drewnoakes

This makes VS format case blocks the way we seem to do them in this repo.

## Before

```c#
switch (foo)
{
    case Bar:
        {
            // block content
            break;
        }
}
```

## After

```c#
switch (foo)
{
    case Bar:
    {
        // block content
        break;
    }
}
```

2022-02-09 17:14 UTC, MiYanni requested changes
I thought something looked odd. Case blocks don't need curly braces. They are only creating inner scopes which aren't necessary in most... *cases* 🤣 (terrible code humor). So, we should likely just strip the curly braces.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/statements/selection-statements#the-switch-statement

## Before

```c#
switch (foo)
{
    case Bar:
        {
            // block content
            break;
        }
}
```

## After

```c#
switch (foo)
{
    case Bar:
        // block content
        break;
}
```

2022-02-09 23:50 UTC, tmeschter commented
I don't think the two are mutually exclusive. I'd rather not have the curly braces if we don't need them, but when we do I'd like them to be aligned with the `case` rather than indented.

2022-02-09 23:51 UTC, tmeschter approved these changes

2022-02-10 02:18 UTC, MiYanni requested changes

2022-02-10 02:18 UTC, MiYanni commented on .editorconfig
> +csharp_indent_case_contents_when_block = false
If we're changing this, I assume it'll produce warnings on the build. This PR should resolve those warnings. My previous comment meant that if you change this and it produces those warnings, then a majority of these cases could just be fixed to no longer contain `{ }`. I'm not saying that this cannot be set to `false`. What I am saying is that setting this to `false` in this PR should contain the changes to remove the extra curly braces in this PR.

2022-02-10 05:16 UTC, drewnoakes commented
Braces can be needed to constrain the scope of variables within the blocks.

```c#
switch (i)
{
    case 1:
        int j = 1;
        break;
    case 2:
        int j = 2; // error
        break;
}

switch (i)
{
    case 1:
    {
        int j = 1;
        break;
    }
    case 2:
    {
        int j = 2; // no error
        break;
    }
}
```

2022-02-10 06:59 UTC, MiYanni approved these changes
As I mentioned in my original comment about the fact that curly braces can be used for scoping, I decided to check the repo if there was even a situation where this occurs. There was only a single usage of braces within the cases in a switch expression in the file `FlagsStringMatcher.cs` and those cases were not scoping any variables.

I went ahead and picked a set of criteria, and looked through the 18 switch statements in C# in the repo. I created a PR here that outlines the criteria I used to update those switch statements.  https://github.com/dotnet/project-system/pull/7910

Since those changes are independent of the `csharp_indent_case_contents_when_block` editorconfig value, when the change in this PR is combined with the changes in my PR, there will no longer be a warning given for the switch expression in `FlagsStringMatcher.cs`.

2022-02-16 13:35 UTC, merged