Preserve environment variable order in launch profiles
dotnet/project-system pull request #8072
Opened 2022-04-13 12:25 UTC by drewnoakes

Fixes #8071

`ILaunchProfile.EnvironmentVariables` is defined as an `ImmutableDictionary<,>`, which does not preserve the order of the items within it. This means we would reorder a user's environment variables between the `launchSettings.json` file and the UI.

Unstable ordering has two problems:

1. It has blocked us from providing a better UI editor for environment variables. We can't have the data reordering beneath us while the user makes edits.
2. User confusion/frustration. We received feedback about this in https://developercommunity.visualstudio.com/t/Dont-Reorder-my-launchSettingsjson-env/1701070

Unfortunately `ILaunchProfile` is a public API, so we cannot modify the collection type used to store environment variables. Therefore, the approach taken to provide stable ordering in this commit can be summarised as:

- Add new state on `LaunchProfile` that tracks the order of keys in the environment variables map.
- Add extension methods on `ILaunchProfile` that produce ordered data when the underlying type is `LaunchProfile`.
- Create static class `ActiveLaunchProfileEnvironmentVariableValueProvider` to own the formatting and parsing of the string property value representation of environment variable name/value pairs.
- Make `LaunchProfile` immutable to provide clearer guarantees of consistency between the collections and the key order array. This required changing quite a bit of test code, and changing how the token replacement works. Ordinarily I'd like to pull a change like this out as a separate commit, but I really wanted those guarantees as part of this change, and I was already too far invested when I realised to pull it out as a separate commit in any reasonable timeframe.

## After

![zygote-after](https://user-images.githubusercontent.com/350947/163179040-e9fdeeda-d702-4506-8dd7-ac06b8e8b485.gif)

See how the order in the UI matches that in the JSON file. Edits made in the text box are stable when committed, and the order is reflected correctly in JSON, meaning this round trips correctly.

2022-04-13 12:31 UTC, drewnoakes commented
@tmeschter we could build on this to introduce:

```c#
public interface ILaunchProfile2
{
    ImmutableArray<KeyValuePair<string, string>> EnvironmentVariables { get; }
    ImmutableArray<KeyValuePair<string, object>> OtherSettings { get; }
}
```

If a launch profile wants stable ordering of these values, they add this interface and we would only invoke these versions of the properties.

In 17.3 we may also wish to further extend `ILaunchProfile2` to support the feature request from #167.

```c#
public interface ILaunchProfile2
{
    ImmutableArray<KeyValuePair<string, string>> EnvironmentVariables { get; }
    ImmutableArray<KeyValuePair<string, object>> OtherSettings { get; }
    bool SkipLoadingReadyToRunImagesDuringDebugging { get; }
}
```

What do you think of this idea? Are you aware of anything else we may like to add to such an interface while we are at it?

2022-04-13 13:03 UTC, drewnoakes commented on src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfile.cs
> +                otherSettingsKeyOrder = otherSettings?.Keys.ToImmutableArray() ?? ImmutableArray<string>.Empty;
Looking again, these should probably sorted alphabetically for consistency with elsewhere.

2022-04-13 13:05 UTC, drewnoakes commented on src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/DebugPropertyPage/ActiveLaunchProfileEnvironmentVariableValueProvider.cs
> -        private static void ParseStringIntoDictionary(string value, Dictionary<string, string> dictionary)
This code appeared twice. Moved a single copy to a new class.

2022-04-13 13:06 UTC, drewnoakes commented on src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/LaunchProfiles/LaunchProfileProjectProperties.cs
> -        private static void ParseStringIntoDictionary(string value, Dictionary<string, string> dictionary)
Here's the other copy.

2022-04-13 16:19 UTC, tmeschter requested changes
In general I like the change, except for the dependency on `Dictionary<string, string>` preserving item order. That's an implementation detail and I am uneasy taking a dependency on that. Could we make use of [OrderedDictionary](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary) instead?

2022-04-13 16:19 UTC, tmeschter commented on src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchProfileExtensions.cs
> +                result.Add(key, dic[key]);
Is your expectation that the dictionary's enumeration order will match the insertion order here? The documentation specifically calls out that the enumeration order is undefined.

2022-04-13 16:26 UTC, tmeschter commented
@drewnoakes I like the idea of an `ILaunchProfile2` that preserves the ordering of environment variables and other settings. However, I'm not sure about combining that with a solution for #167 as I have further thoughts on it, which I'll raise on that issue.

2022-04-13 16:29 UTC, tmeschter commented
@drewnoakes Oh, and I think the `ActiveLaunchProfile*` types are probably all dead code. They date back to when we were still showing the _active_ launch profile in the new property pages. They shouldn't be used at all when using the Launch Profile UI. I need to make sure the WebTools team doesn't have any lingering dependencies on them and then they can be deleted.

2022-04-13 21:17 UTC, drewnoakes commented
> In general I like the change, except for the dependency on `Dictionary<string, string>` preserving item order. That's an implementation detail and I am uneasy taking a dependency on that. Could we make use of [OrderedDictionary](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary) instead?

OrderedDictionary will not help. It reorders items based on the key.

While the fact that Dictionary preserves insertion order is something that could theoretically change, there is no way that would ever happen. It would break far too many programs.

2022-04-13 21:28 UTC, tmeschter commented
> OrderedDictionary will not help. It reorders items based on the key.

That's [SortedDictionary](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sorteddictionary-2?view=net-6.0). From the [OrderedDictionary ](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary?view=net-6.0) docs:

> The elements of an [OrderedDictionary](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary?view=net-6.0) are not sorted by the key, unlike the elements of a [SortedDictionary<TKey,TValue>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sorteddictionary-2?view=net-6.0) class. You can access elements either by the key or by the index.

Also, it is not at all obvious that a `Dictionary` preserves order, or that we are using it specifically for its order-preserving properties. That's going to lead to maintenance problems down the line. Even if `Dictionary` works in practice, I'd rather a type that is explicit about the behavior we need.

2022-04-13 21:52 UTC, drewnoakes commented
My mistake. I shouldn't jump on the computer until I've woken up a little :)

I'll take a look to see whether using OrderedDictionary helps. There is a public API that uses Dictionary that may make that challenging.

It might be that the `ILaunchProfile2` approach is clearer overall.

2022-04-14 03:49 UTC, drewnoakes commented on src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/ILaunchProfileExtensions.cs
> +            if (profile.EnvironmentVariables is null)
When I converted the others, this had a different implementation. It changed since then. I've made it a switch expression too, thanks.

2022-04-14 20:26 UTC, tmeschter commented
Yeah, I think the `ILaunchProfile2` approach might be best. That will also allow WebTools and others to opt into the new system.

2022-04-15 02:26 UTC, drewnoakes commented
I started on it yesterday and it feels like a good approach. I'll have an update for this early next week.

2022-04-18 14:49 UTC, drewnoakes commented
I spent some time on this and ended up reducing the number of concepts in this part of the code quite a bit. There's an `ILaunchProfile2` type now that preserves order.

There are fewer types now, and fewer constructors on those types. More stuff is immutable, and less copying occurs when we can determine that copies are not needed.

The diff is quite heavy. It may be easier to review commit by commit. Or perhaps pull it down, test it, and step through some operations. I've spent quite a bit of time testing it and am happy with it as a foundation for work towards #7330. I'll dust off my old branch. Now that the underlying data is stable, it should be easier to get that branch ready for review.

2022-04-18 14:50 UTC, drewnoakes commented
I'd also point out that it wasn't possible to completely rid ourselves of a dependency on the ordering behaviour of `Dictionary<,>`. Doing so would require versioning `IWritableLaunchSettings` and `IWritableLaunchProfile`.

2022-04-19 07:46 UTC, drewnoakes commented
I forgot to mention that I looked into `OrderedDictionary` and it's not a generic type. I don't think the loss of type safety is worth it in this case.

2022-04-19 20:16 UTC, tmeschter approved these changes

2022-04-20 00:05 UTC, drewnoakes commented on src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchProfileExtensions.cs
> +            if (profile is ILaunchProfile2 lp2)
Yes, thank you. I'll add a unit test for this, and also review other places where we special-case `ILaunchProfile2` to make sure nothing else was missed.

2022-04-20 01:54 UTC, merged